export const modulesData = [
  {
    nr: 1,
    titel: 'Toegankelijkheid in één oogopslag',
    subtitel: 'Basiskennis · wetgeving · drie vormen',
    duur: '15 min',
    intro: 'Toegankelijkheid gaat over meer dan een rolstoelhellingbaan. In deze module ontdek je wat toegankelijkheid écht betekent, welke wet- en regelgeving er geldt en hoe je de drie vormen van toegankelijkheid herkent in jouw eigen organisatie.',
    inhoud: [
      { type: 'tekst', titel: 'Toegankelijkheid is een grondrecht', tekst: 'Toch is het in de cultuursector nog lang geen vanzelfsprekendheid. Veel culturele instellingen zijn gebouwd in een tijd waarin toegankelijkheid geen prioriteit was — en dat merk je. Smalle deuren, hoge drempels, websites die niet werken met een schermlezer, communicatie die alleen mensen bereikt die al bekend zijn met het aanbod.' },
      { type: 'foto', url: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=1200', alt: 'Museum entree' },
      { type: 'tekst', titel: 'Verder dan fysieke drempels', tekst: 'Toegankelijkheid gaat over wie zich welkom voelt. Over wie de weg weet te vinden. Over wie zich herkent in het aanbod, de communicatie en de mensen die er werken. De Nederlandse overheid heeft zich met het ratificeren van het VN-verdrag inzake de rechten van personen met een handicap (2016) verplicht om gelijke participatie voor iedereen te waarborgen. Voor culturele instellingen betekent dit: je bent verplicht om stappen te zetten — niet als gunst, maar als recht.' },
      { type: 'quote', tekst: 'Wij dachten dat we toegankelijk waren. Totdat we mensen met een beperking vroegen mee te lopen door ons gebouw. Na twintig minuten hadden we een lijst van dertig verbeterpunten.', auteur: 'Directeur middelgroot museum, deelnemer InCultuur programma' },
      { type: 'foto', url: 'https://images.unsplash.com/photo-1573497491208-6b1acb260507?w=1200', alt: 'Diverse groep mensen in gesprek' },
      { type: 'tekst', titel: 'Drie vormen die elkaar versterken', tekst: 'Fysieke toegankelijkheid gaat over de gebouwde omgeving. Kan iemand in een rolstoel zelfstandig naar binnen? Is er een invalidentoilet? Zijn er geleidelijnen voor mensen met een visuele beperking? Fysieke toegankelijkheid is vaak het meest zichtbaar, maar slechts één onderdeel van het geheel.' },
      { type: 'tekst', titel: 'Digitaal en sociaal', tekst: 'Digitale toegankelijkheid gaat over je online aanwezigheid. Is je website te gebruiken met een schermlezer? Hebben je video\'s ondertitels? Sociale toegankelijkheid gaat over de vraag of mensen zich welkom voelen — een gebouw kan perfect toegankelijk zijn, maar als de sfeer niet uitnodigend is, zullen veel mensen toch afhaken. Echte inclusie vraagt om een integrale aanpak.' },
    ],
    leerdoelen: [
      'Uitleggen wat toegankelijkheid betekent in de cultuursector',
      'De belangrijkste wet- en regelgeving benoemen',
      'De drie vormen van toegankelijkheid onderscheiden',
      'Een eerste inschatting maken van je eigen organisatie',
    ],
    quiz: [
      {
        vraag: 'Welke wet verplicht organisaties om toegankelijkheid te waarborgen?',
        opties: ['De Wet gelijke behandeling', 'Het VN-verdrag Handicap', 'De Algemene wet bestuursrecht', 'De Wet maatschappelijke ondersteuning'],
        correct: 1,
        toelichtingen: [
          'De Wet gelijke behandeling biedt wel bescherming, maar is niet de meest directe verplichting voor toegankelijkheid.',
          'Correct! Het VN-verdrag inzake de rechten van personen met een handicap (2006) verplicht landen om gelijke participatie te waarborgen. Nederland ratificeerde dit in 2016.',
          'De Algemene wet bestuursrecht regelt de verhouding tussen overheid en burger, maar gaat niet specifiek over toegankelijkheid.',
          'De Wet maatschappelijke ondersteuning richt zich op zorg en ondersteuning, niet op toegankelijkheid van culturele instellingen.',
        ],
      },
      {
        vraag: 'Welke drie vormen van toegankelijkheid zijn er?',
        opties: ['Fysiek, digitaal en sociaal', 'Visueel, auditief en motorisch', 'Intern, extern en financieel', 'Architectonisch, communicatief en organisatorisch'],
        correct: 0,
        toelichtingen: [
          'Correct! De drie vormen zijn fysiek (gebouw en omgeving), digitaal (online aanwezigheid) en sociaal (welkom voelen). Samen vormen ze een integraal beeld.',
          'Visueel, auditief en motorisch zijn soorten beperkingen, geen vormen van toegankelijkheid.',
          'Intern, extern en financieel is geen gangbare indeling van toegankelijkheid.',
          'Dit zijn geen erkende vormen van toegankelijkheid in de cultuursector.',
        ],
      },
      {
        vraag: 'Wat verstaan we onder sociale toegankelijkheid?',
        opties: ['Een toegankelijke website', 'Een goed bereikbare locatie', 'Een omgeving waar iedereen zich welkom voelt', 'Voldoende parkeerplaatsen'],
        correct: 2,
        toelichtingen: [
          'Een toegankelijke website valt onder digitale toegankelijkheid, niet sociale toegankelijkheid.',
          'Een goed bereikbare locatie valt onder fysieke toegankelijkheid.',
          'Correct! Sociale toegankelijkheid gaat over of mensen zich welkom en geaccepteerd voelen — ongeacht achtergrond, beperking of identiteit.',
          'Parkeerplaatsen vallen onder fysieke toegankelijkheid.',
        ],
      },
    ],
    actiepuntTekst: 'Hoe toegankelijk is jouw organisatie al? Geef per thema aan in welke mate dit al aanwezig is in jouw instelling. Schuif de balk naar de score die het beste bij jullie situatie past.',
    actiepuntTip: 'Wees eerlijk — deze scan is voor jezelf. De uitkomst helpt je om te bepalen waar je als eerste mee aan de slag kunt.',
    schuivers: [
      { titel: 'Fysieke toegankelijkheid', subtitel: 'Ingang, toilet, lift, routing — kan iedereen zelfstandig binnen komen en rond bewegen?' },
      { titel: 'Digitale toegankelijkheid', subtitel: 'Website, social media, ticketshop — werkt alles ook voor mensen met een beperking?' },
      { titel: 'Sociale toegankelijkheid', subtitel: 'Voelt iedereen zich welkom? Is diversiteit zichtbaar in team en aanbod?' },
      { titel: 'Communicatie', subtitel: 'Gebruik je begrijpelijke taal, voldoende contrast en bereik je diverse doelgroepen?' },
      { titel: 'Programmering', subtitel: 'Is je aanbod toegankelijk en relevant voor mensen met verschillende achtergronden en beperkingen?' },
      { titel: 'Beleid', subtitel: 'Is toegankelijkheid verankerd in het organisatiebeleid en de strategie?' },
      { titel: 'Medewerkers', subtitel: 'Hebben medewerkers kennis van en bewustzijn over toegankelijkheid?' },
    ],
    actiepunt: 'Maak een snelle scan van jouw organisatie of locatie: welke toegankelijkheidsaspecten zijn aanwezig, welke ontbreken? Noteer minimaal drie verbeterpunten en bespreek deze met een collega.',
  },
  {
    nr: 2,
    titel: 'Publieksbenadering zonder drempels',
    subtitel: 'Communicatie · inclusie · doelgroepen',
    duur: '15 min',
    video: 'https://www.youtube.com/embed/LL3PUYa-Dpw',
    videotekst: 'Toegankelijkheid is niet alleen een taak voor een handvol specialisten. Het vraagt om een cultuuromslag in de hele organisatie — van programmeurs tot HR-medewerkers, van de communicatieafdeling tot de barmensen. Juist de nieuwe generatie medewerkers en leidinggevenden in de kunst- en cultuursector heeft de kans én de verantwoordelijkheid om anders te denken. Om uit de eigen bubbel te stappen. Om niet te vragen "wie sluit ik uit?" maar "hoe zorg ik dat iedereen zich welkom voelt?". Toegankelijkheid begint niet bij een beleidsplan — het begint bij jou.',
    intro: 'Hoe bereik je mensen die je nu nog niet bereikt? In deze module leer je hoe je inclusief communiceert, welke drempels mensen ervaren om naar een culturele instelling te gaan en hoe je die drempels kunt wegnemen.',
    leerdoelen: [
      'Toegankelijk communiceren in taal en beeld',
      'Verschillende doelgroepen herkennen en aanspreken',
      'Drempels in communicatie identificeren',
      'Een concrete communicatieverbetering doorvoeren',
    ],
    quiz: [
      {
        vraag: 'Wat is een belangrijk kenmerk van toegankelijke communicatie?',
        opties: ['Veel vakjargon gebruiken', 'Korte zinnen en begrijpelijke taal', 'Alleen digitale kanalen inzetten', 'Zo veel mogelijk informatie geven'],
        correct: 1,
        toelichtingen: [
          'Vakjargon werkt juist drempelverhoging — het sluit mensen uit die niet vertrouwd zijn met de terminologie.',
          'Correct! Helder taalgebruik, korte zinnen en een logische structuur maken communicatie toegankelijk voor iedereen.',
          'Alleen digitaal inzetten sluit mensen uit die minder digitaal vaardig zijn of geen internet hebben.',
          'Te veel informatie leidt juist tot overprikkeling en afhaken — minder is meer bij toegankelijke communicatie.',
        ],
      },
      {
        vraag: 'Welke doelgroep wordt het vaakst over het hoofd gezien in culturele communicatie?',
        opties: ['Jongeren onder de 25', 'Mensen met een beperking', 'Senioren boven de 65', 'Gezinnen met kinderen'],
        correct: 1,
        toelichtingen: [
          'Jongeren worden juist vaak actief aangesproken via social media en jongerenprogrammering.',
          'Correct! Mensen met een beperking vormen ongeveer 15% van de bevolking maar worden vaak niet meegenomen in communicatieplanning.',
          'Senioren krijgen steeds meer aandacht via specifieke programma\'s en middagen.',
          'Gezinnen met kinderen worden actief bereikt via familietickets en kinderprogrammering.',
        ],
      },
      {
        vraag: 'Wat is de belangrijkste reden waarom mensen met een beperking culturele instellingen mijden?',
        opties: ['Te duur', 'Geen interesse', 'Onzekerheid over toegankelijkheid', 'Te ver weg'],
        correct: 2,
        toelichtingen: [
          'Prijs speelt een rol, maar is niet de grootste drempel voor mensen met een beperking specifiek.',
          'Onderzoek toont aan dat interesse er zeker is — de drempel zit in praktische onzekerheid, niet in motivatie.',
          'Correct! Mensen weten niet of ze binnen kunnen, of er een toilet is, of de voorstelling ondertiteld is. Duidelijke informatie verlaagt deze drempel enorm.',
          'Bereikbaarheid speelt mee, maar is niet de grootste drempel — onzekerheid over toegankelijkheid staat op nummer één.',
        ],
      },
    ],
    actiepunt: 'Pas één communicatie-uiting aan volgens toegankelijke richtlijnen. Denk aan je website, een flyer of een social media post.',
    actiepuntTip: 'Gebruik de gratis tool van Accessibility Checker om je website te scannen op toegankelijkheid.',
  },
  {
    nr: 3,
    titel: 'Prikkelarm en voelbaar',
    subtitel: 'Sensorisch · ruimte · beleving',
    duur: '15 min',
    intro: 'Niet iedereen ervaart een ruimte op dezelfde manier. In deze module leer je hoe je een prikkelarme omgeving creëert en welke kleine aanpassingen een groot verschil maken.',
    leerdoelen: [
      'Uitleggen wat prikkelarme omgevingen zijn',
      'Sensorische uitdagingen herkennen in jouw locatie',
      'Concrete aanpassingen doorvoeren in licht, geluid en bewegwijzering',
      'Een prikkelarme route of hoek ontwerpen',
    ],
    quiz: [
      {
        vraag: 'Welke aanpassing heeft de grootste impact op een prikkelarme omgeving?',
        opties: ['Nieuwe vloerbedekking', 'Dimbaar licht en geluidsdemping', 'Meer zitplaatsen', 'Andere kleurstelling'],
        correct: 1,
        toelichtingen: [
          'Vloerbedekking kan geluid dempen maar heeft minder impact dan directe licht- en geluidsaanpassingen.',
          'Correct! Licht en geluid zijn de grootste bronnen van prikkels. Dimbaar licht en geluidsdemping hebben de meeste impact.',
          'Meer zitplaatsen helpt bij vermoeidheid maar pakt de sensorische prikkels zelf niet aan.',
          'Kleur kan een rol spelen maar heeft minder impact dan licht en geluid.',
        ],
      },
      {
        vraag: 'Voor welke doelgroep zijn prikkelarme voorstellingen primair bedoeld?',
        opties: ['Senioren', 'Kinderen onder de 6', 'Mensen met autisme of sensorische gevoeligheid', 'Mensen met een visuele beperking'],
        correct: 2,
        toelichtingen: [
          'Senioren profiteren soms van rustigere omgevingen, maar prikkelarme voorstellingen zijn niet primair voor hen bedoeld.',
          'Kleine kinderen hebben andere behoeften — prikkelarme voorstellingen zijn niet specifiek voor hen ontworpen.',
          'Correct! Mensen met autisme of sensorische gevoeligheid profiteren het meest. Maar ook mensen met ADHD of chronische vermoeidheid vinden het prettig.',
          'Mensen met een visuele beperking hebben andere aanpassingen nodig zoals audiodescriptie.',
        ],
      },
      {
        vraag: 'Wat is een rustige hoek in een museum?',
        opties: ['Een afgesloten ruimte voor medewerkers', 'Een plek waar bezoekers even kunnen herstellen van prikkels', 'Een stille leeszaal', 'Een ruimte voor groepsbezoeken'],
        correct: 1,
        toelichtingen: [
          'Een ruimte voor medewerkers is niet toegankelijk voor bezoekers.',
          'Correct! Een rustige hoek is een plek waar bezoekers even kunnen decomprimeren — weg van drukte en geluid.',
          'Een leeszaal heeft een specifieke functie; een rustige hoek is laagdrempeliger en breder toegankelijk.',
          'Groepsruimtes zijn juist drukker — het tegenovergestelde van wat een rustige hoek beoogt.',
        ],
      },
    ],
    actiepunt: 'Voer een kleine aanpassing uit in een ruimte of evenement. Denk aan het dimmen van verlichting of het toevoegen van duidelijke bewegwijzering.',
    actiepuntTip: 'Betrek een medewerker met persoonlijke ervaring bij het ontwerpen van de aanpassing.',
  },
  {
    nr: 4,
    titel: 'Samenwerken met ervaringsdeskundigen',
    subtitel: 'Co-creatie · inclusie · samenwerking',
    duur: '15 min',
    intro: 'De beste manier om toegankelijkheid te verbeteren is door samen te werken met mensen die het zelf ervaren. In deze module leer je hoe je ervaringsdeskundigen betrekt op een gelijkwaardige manier.',
    leerdoelen: [
      'Uitleggen waarom ervaringsdeskundigen onmisbaar zijn',
      'Weten hoe je een inclusief samenwerkingsproces opzet',
      'Valkuilen in co-creatie herkennen en vermijden',
      'Een eerste stap zetten naar samenwerking met ervaringsdeskundigen',
    ],
    quiz: [
      {
        vraag: 'Wat is de belangrijkste valkuil bij samenwerken met ervaringsdeskundigen?',
        opties: ['Te veel vergaderen', 'Ervaringsdeskundigen alleen raadplegen aan het einde', 'Geen budget reserveren', 'Te vroeg beginnen'],
        correct: 1,
        toelichtingen: [
          'Te veel vergaderen is vervelend maar niet de grootste valkuil bij co-creatie.',
          'Correct! Ervaringsdeskundigen alleen aan het einde raadplegen maakt hun input cosmetisch. Betrek ze vanaf het begin.',
          'Budget is belangrijk maar de timing van betrokkenheid is de meest gemaakte structurele fout.',
          'Te vroeg beginnen is geen valkuil — vroeg beginnen is juist aan te raden.',
        ],
      },
      {
        vraag: 'Wat betekent co-creatie?',
        opties: ['Iets maken voor een specifieke doelgroep', 'Iets maken samen met de doelgroep', 'Iets laten maken door een extern bureau', 'Iets kopiëren van een ander'],
        correct: 1,
        toelichtingen: [
          'Iets maken vóór een doelgroep is niet co-creatie — de doelgroep is dan geen partner maar ontvanger.',
          'Correct! Co-creatie betekent samen maken. De ervaringsdeskundige is een gelijkwaardige partner, geen informant.',
          'Een extern bureau inschakelen is uitbesteden, niet co-creëren.',
          'Kopiëren heeft niets met co-creatie te maken.',
        ],
      },
      {
        vraag: 'Hoe vergoed je ervaringsdeskundigen het best voor hun inzet?',
        opties: ['Alleen met een bedankje', 'Met een passende financiële vergoeding', 'Met gratis toegangskaarten', 'Met een certificaat'],
        correct: 1,
        toelichtingen: [
          'Een bedankje erkent de bijdrage niet serieus — ervaringsdeskundigen leveren professionele kennis.',
          'Correct! Een financiële vergoeding is de meest respectvolle erkenning. Kennis heeft waarde en verdient eerlijke beloning.',
          'Toegangskaarten zijn een leuk gebaar maar geen serieuze vergoeding voor professionele inzet.',
          'Een certificaat heeft symbolische waarde maar vervangt geen eerlijke financiële compensatie.',
        ],
      },
    ],
    actiepunt: 'Plan een gesprek of brainstorm met minstens één ervaringsdeskundige over toegankelijkheid in jouw organisatie.',
    actiepuntTip: 'Neem contact op met InCultuur voor een lijst van ervaringsdeskundigen die beschikbaar zijn voor samenwerking.',
  },
]